Fix panels hiding after resizing
storybook-eol/storybook-ui pull request #67
Opened 2017-01-07 17:46 UTC by evgenykochetkov

Right now if you resize a panel and then try to hide it(by pressing the shortcut), it will only hide panel's contents, the panel itself still occupies space.

This PR fixes it by not using SplitPane when we need to render just one panel.

Another approach would be to add support for hiding panels in `react-split-pane`. Not sure which one is the best.

2017-01-11 00:50 UTC, arunoda commented
This is great.
I think this approach is fine.

I need only small UI fix before we could get this.
see: 
![screen shot 2017-01-11 at 6 15 06 am](https://cloud.githubusercontent.com/assets/50838/21830882/edb7fade-d7c5-11e6-9516-8b6bc01d2a24.png)

Here we need to add some more margin to the panel in the right.

2017-04-02 00:20 UTC, benediktvaldez requested changes
This seems to run fine, and fix the issue, so good job on that!

I did try running it on an existing project I have, where I'm using the options addon, and noticed it seems to be causing problems when using either `showLeftPanel` or `showDownPanel`, as in the keyboard shortcut won’t work anymore (regardless of the option set, you’re stuck with the option set by the options addon).

I created a repo where you can replicate the problem
https://github.com/benediktvaldez/storybook-ui-67

2017-04-02 15:19 UTC, UsulPro commented
I tried to reproduce this issue with `storybook-addon-options` and find out that every changing of `showLeftPanel` or `showDownPanel` cause the page reloading

It happens when `leftPanel()` or `downPanel()` appears in another place of DOM structure.
The result of page reloading is re-running the code from `.storybook\config.js`. 

That's why
> you’re stuck with the option set by the options addon

I believe that the page reloading after keyboard shortcut applying is something undesirable :open_mouth:

some minor experiments showed that we can prevent reloading if keep the nesting `div` structure or something around this... maybe it's possible to find any better solution for this..? :blush:

Anyway it seems that it's more issue with this PR than with  `storybook-addon-options`?

BTW `react-split-pane` is now available as a separated [package](https://github.com/tomkp/react-split-pane). I didn't try it deeply but maybe the latest version already solves this issue?

2017-04-02 15:21 UTC, UsulPro commented on src/modules/ui/components/layout/index.js
> +            ? (
this causes a page reload

2017-04-10 05:10 UTC, UsulPro commented
Looks like this PR #59 solved the similar issue

2017-04-15 15:08 UTC, ndelangen commented
Hey @evgenykochetkov  

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.
We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

That'd be awesome, thanks!

2017-04-15 15:08 UTC, closed without merging

2017-04-15 15:43 UTC, evgenykochetkov commented
Oh hi @ndelangen!
I was just about to close this PR anyway because I'd rather try a different approach to this issue.
Great news about the mono-repo, I will gladly do a PR there ❤️